#include "easybasics.h"

IMPL_ARRLIST(size_t);
IMPL_ARRLIST(int);
IMPL_ARRLIST(float);
IMPL_ARRLIST(char);
IMPL_ARRLIST(uint32_t);
IMPL_ARRLIST(int32_t);
IMPL_ARRLIST(uint64_t);
IMPL_ARRLIST(int64_t);
IMPL_ARRLIST(uint16_t);
IMPL_ARRLIST(int16_t);
IMPL_ARRLIST(uint8_t);
IMPL_ARRLIST(int8_t);

IMPL_ARRLIST_NAMED(voidPtr, void*);

IMPL_PQUEUE(size_t);
IMPL_PQUEUE(int);
IMPL_PQUEUE(float);
IMPL_PQUEUE(char);
IMPL_PQUEUE(uint32_t);
IMPL_PQUEUE(int32_t);
IMPL_PQUEUE(uint64_t);
IMPL_PQUEUE(int64_t);
IMPL_PQUEUE(uint16_t);
IMPL_PQUEUE(int16_t);
IMPL_PQUEUE(uint8_t);
IMPL_PQUEUE(int8_t);

IMPL_EASYSORT(int);
IMPL_EASYSORT(float);
