name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests (Linux)
        if: runner.os == 'Linux'
        run: bash test.sh

      - name: Run tests (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: test.bat

      - name: Run tests (macOS)
        if: runner.os == 'macOS'
        run: |
          mkdir -p build
          curl -sL -o build/tiny_macos.bin https://github.com/JHeflinger/tiny/raw/refs/heads/main/bin/tiny_macos.bin
          chmod +x build/tiny_macos.bin
          ./build/tiny_macos.bin -r
